# Generated by Django 3.2.10 on 2021-12-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_mobile_jan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
