# Generated by Django 3.2.10 on 2021-12-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_alter_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='jan_code',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model',
            field=models.CharField(max_length=200),
        ),
    ]
