# Generated by Django 3.2.10 on 2021-12-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_auto_20211229_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='jan_code',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
